version: '3'

services:
    web:
        image: webdevops/php-apache:latest
        ports:
            - ${IP}:80:80
            - ${IP}:443:443
        volumes:
            - ./html:/app
        links:
            - db
        environment:
            WEB_DOCUMENT_ROOT: /app/web
        container_name: ${PROJECT_NAME}_web

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:latest
        container_name: ${PROJECT_NAME}_db_admin
        restart: always
        ports:
            - ${IP}:8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'

    db:
        image: mysql:latest # or mariadb https://hub.docker.com/_/mariadb
        container_name: ${PROJECT_NAME}_db
        volumes:
            - ./db_data:/var/lib/mysql # to persits database so we do not lose data when stop/starting container
        ports:
            - ${IP}:3306:3306 # change ip if required
        command: ['--default_authentication_plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ADMIN: root
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'

volumes:
    html:
    db_data:
